DROP TABLE user_roles IF EXISTS;
DROP TABLE dishes IF EXISTS;
DROP TABLE users IF EXISTS;
DROP TABLE history IF EXISTS;
DROP TABLE restaurants IF EXISTS;
DROP SEQUENCE global_seq IF EXISTS;

CREATE SEQUENCE GLOBAL_SEQ AS INTEGER START WITH 100000;

CREATE TABLE users
(
    id                  INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
    name                VARCHAR(255)            NOT NULL,
    email               VARCHAR(255)            NOT NULL,
    password            VARCHAR(255)            NOT NULL,
    registered          TIMESTAMP DEFAULT now() NOT NULL,
    enabled             BOOLEAN DEFAULT TRUE    NOT NULL,
    date_vote           TIMESTAMP DEFAULT NULL,
    restaurant_id_vote  INTEGER DEFAULT null
);
CREATE UNIQUE INDEX users_unique_email_idx ON users(email);

CREATE TABLE user_roles
(
    user_id                 INTEGER NOT NULL,
    role                    VARCHAR(255),
    CONSTRAINT user_role_idx UNIQUE (user_id, role),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE restaurants
(
    id                      INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
    name                    VARCHAR(255)            NOT NULL,
    vote                    INTEGER DEFAULT 0       NOT NULL,
    admin_id                INTEGER,
    CONSTRAINT rest_name_idx UNIQUE (name)
);

CREATE TABLE dishes
(
    id                      INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
    restaurant_id           INTEGER                 ,
    name                    VARCHAR(255)            NOT NULL,
    cost                    INTEGER DEFAULT 0       NOT NULL,
    CONSTRAINT dish_idx UNIQUE (restaurant_id, name),
    FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE
);

CREATE TABLE history
(
    id                      INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
    restaurant_name         VARCHAR(255)            NOT NULL,
    vote_date               TIMESTAMP DEFAULT now() NOT NULL,
    vote                    INTEGER DEFAULT 0       NOT NULL,
    menu                    VARCHAR(500)            NOT NULL
)